"""Container image signatures, provenance and SBOM association (Stage 12).

Standard tooling only: **cosign** (Sigstore) signs the image digest and attaches two
in-toto attestations:

* **SLSA provenance v1** (``--type slsaprovenance1``): git commit, workflow/run, builder,
  build parameters and the SBOM digest;
* **CycloneDX SBOM** of the image (``--type cyclonedx``), generated by Trivy.

``scripts/image_sign.sh`` does the signing and writes an *evidence* file that the signed
release manifest records. This module **verifies**, always by digest, never by tag:

1. the image-signing public key is the one the evidence names (fingerprint);
2. ``cosign verify``: a valid signature over exactly this digest;
3. ``cosign verify-attestation --type slsaprovenance1``: signed provenance whose subject
   is this digest and whose predicate hashes to the recorded value (and, when given,
   names the expected git commit);
4. ``cosign verify-attestation --type cyclonedx``: a signed SBOM for this digest that
   hashes to the recorded SBOM digest.

A tampered image (another digest), a missing or foreign signature, or edited provenance or
SBOM fails a check. Keys: a dedicated image key (``VAULT_KEY_IMAGE`` via cosign's
``hashivault://`` KMS, or a cosign key file), never the model, audit, release or API key.

**Transparency log.** Signing uses ``--tlog-upload=false``, so no public Rekor entry is
created (the registry is private), and verification passes ``--insecure-ignore-tlog``.
Trust therefore rests on the key alone; there is no public, append-only record of what was
signed. Keyless signing (Fulcio + Rekor) is the alternative for a public registry.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import shutil
import subprocess  # nosec B404 - cosign with a fixed argument list, no shell
from pathlib import Path
from typing import Any

from cryptography.hazmat.primitives import serialization

from fraud_ai.trust.keys import TrustError

SLSA_PREDICATE = "https://slsa.dev/provenance/v1"
CYCLONEDX_PREDICATE = "https://cyclonedx.org/bom"


def canonical_sha256(value: Any) -> str:
    """SHA-256 of canonical JSON (what the evidence records for predicates)."""
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()
    ).hexdigest()


def key_fingerprint(pem: bytes) -> str:
    """``sha256:`` over the DER SubjectPublicKeyInfo of a PEM public key."""
    try:
        key = serialization.load_pem_public_key(pem)
    except ValueError:
        raise TrustError("not a PEM public key") from None
    der = key.public_bytes(
        serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
    )
    return "sha256:" + hashlib.sha256(der).hexdigest()


def cosign_binary() -> str:
    binary = os.environ.get("COSIGN_BINARY") or shutil.which("cosign")
    if not binary:
        raise TrustError("cosign is not installed (set COSIGN_BINARY or put cosign on PATH)")
    return binary


def _insecure_registry_flags(image: str) -> list[str]:
    host = image.split("/", 1)[0]
    if host.startswith(("localhost", "127.0.0.1")):
        return ["--allow-insecure-registry", "--allow-http-registry"]
    return []


def _cosign(args: list[str], timeout: float = 120.0) -> subprocess.CompletedProcess[str]:
    return subprocess.run(  # nosec B603 # noqa: S603 - fixed binary, argument list
        [cosign_binary(), *args],
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
        env={**os.environ, "COSIGN_YES": "true"},
    )


def _statements(stdout: str) -> list[dict[str, Any]]:
    """Decode the in-toto statements from ``cosign verify-attestation`` output."""
    out = []
    for line in stdout.splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        envelope = json.loads(line)
        payload = envelope.get("payload")
        if payload:
            out.append(json.loads(base64.b64decode(payload)))
    return out


def _subject_ok(statement: dict[str, Any], digest: str) -> bool:
    want = digest.removeprefix("sha256:")
    return any(
        (s.get("digest") or {}).get("sha256") == want for s in statement.get("subject") or []
    )


def verify_image(
    evidence: dict[str, Any],
    *,
    public_key: Path,
    expected_commit: str | None = None,
) -> dict[str, str]:
    """Run every check; return ``{name: "ok ..." | "FAILED: ..."}`` (never raises for a
    failed check; raises :class:`TrustError` only when cosign itself is missing)."""
    checks: dict[str, str] = {}
    digest = str(evidence["digest"])
    ref = f"{evidence['image']}@{digest}"
    flags = _insecure_registry_flags(str(evidence["image"]))
    try:
        fingerprint = key_fingerprint(public_key.read_bytes())
    except (OSError, TrustError) as exc:
        return {"image_signature": f"FAILED: cannot read the image public key ({exc})"}
    if fingerprint != evidence.get("signing_key_fingerprint"):
        checks["image_key"] = (
            f"FAILED: {public_key} is {fingerprint[:23]}…, the evidence names "
            f"{str(evidence.get('signing_key_fingerprint'))[:23]}…"
        )
    else:
        checks["image_key"] = f"ok ({fingerprint[:23]}…)"

    signed = _cosign(["verify", "--key", str(public_key), "--insecure-ignore-tlog", *flags, ref])
    if signed.returncode != 0:
        checks["image_signature"] = "FAILED: " + (signed.stderr.strip().splitlines() or ["?"])[-1]
    else:
        try:
            payloads = [json.loads(x) for x in signed.stdout.splitlines() if x.startswith("[")]
            digests = {
                p["critical"]["image"]["docker-manifest-digest"]
                for batch in payloads
                for p in batch
            }
        except (ValueError, KeyError, TypeError):
            digests = set()
        checks["image_signature"] = (
            f"ok (signature over {digest[:19]}…)"
            if digest in digests
            else f"FAILED: signature payload names {sorted(digests)}"
        )

    for name, kind, recorded in (
        ("image_provenance", "slsaprovenance1", evidence.get("provenance_sha256")),
        ("image_sbom", "cyclonedx", evidence.get("sbom_sha256")),
    ):
        result = _cosign(
            [
                "verify-attestation",
                "--key",
                str(public_key),
                "--type",
                kind,
                "--insecure-ignore-tlog",
                *flags,
                ref,
            ]
        )
        if result.returncode != 0:
            checks[name] = "FAILED: " + (result.stderr.strip().splitlines() or ["?"])[-1]
            continue
        try:
            statements = _statements(result.stdout)
        except ValueError:
            checks[name] = "FAILED: unreadable attestation"
            continue
        matching = [
            s
            for s in statements
            if _subject_ok(s, digest) and canonical_sha256(s.get("predicate")) == recorded
        ]
        if not matching:
            checks[name] = "FAILED: no attestation for this digest with the recorded content"
            continue
        if name == "image_provenance" and expected_commit:
            deps = (
                (matching[0].get("predicate") or {})
                .get("buildDefinition", {})
                .get("resolvedDependencies", [])
            )
            commits = {(d.get("digest") or {}).get("gitCommit") for d in deps}
            if expected_commit not in commits:
                checks[name] = f"FAILED: provenance does not name commit {expected_commit[:12]}"
                continue
        checks[name] = f"ok ({kind}, predicate sha256 {str(recorded)[:12]}…)"
    return checks
